---
server.port: 5000

#spring.h2.console.enabled: true
#spring.datasource.url: jdbc:h2:file:test;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.username: test
#spring.datasource.password: test
#spring.datasource.driverClassName: org.h2.Driver

interestingItemsFile: InterestingItems.csv
#interestingItemsFile: implants.csv
#interestingItemsFile: dummy_InterestingItems.csv
desiredMargin: 1.3

importSource:
  regionId: 10000043
  regionName: "Domain"
  systemId: 30002187
  systemName: "Amarr"
  stationId: 60008494
  stationName: "Amarr VIII (Oris) - Emperor Family Academy"

importDestination:
  regionId: 10000014
  regionName: "Catch"
  systemId: 30001198
  systemName: "GE-8JV"
  stationId: 61000182
  stationName: "GE-8JV"

# Fort structure Id: 1023729674815
