---
server.port: 5000

importSource:
  regionId: 10000043
  regionName: "Domain"
  systemId: 30002187
  systemName: "Amarr"
  stationId: 60008494
  stationName: "Amarr VIII (Oris) - Emperor Family Academy"

importDestination:
  regionId: 10000014
  regionName: "Catch"
  systemId: 30001198
  systemName: "GE-8JV"
  stationId: 61000182
  stationName: "GE-8JV"

interestingItemIds:
  - 2205
  - 2456
  - 2466
  - 2488
  - 2185
  - 2175
  - 21640
  - 21638
  - 2195
  - 2478
  - 2446
  - 2436
  - 28197
  - 28199
  - 31870
  - 28205
  - 28207
  - 28215
  - 28211
  - 28213
  - 28209
  - 31876
